In [2]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [5]:
np.full(10,2.2)

array([2.2, 2.2, 2.2, 2.2, 2.2, 2.2, 2.2, 2.2, 2.2, 2.2])

In [6]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [7]:
a[2]

np.int64(3)

In [8]:
a[2]=5

In [9]:
a

array([1, 2, 5, 4, 5])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
np.linspace(0,2,11)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [13]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
n=np.array([[1,2],[4,5]])

In [15]:
n

array([[1, 2],
       [4, 5]])

In [16]:
n[1][0]

np.int64(4)

In [17]:
n[1,1]

np.int64(5)

In [18]:
n[1]

array([4, 5])

In [19]:
n[:,1]

array([2, 5])

In [20]:
np.random.seed(2)
100*np.random.rand(1,4)

array([[43.59949021,  2.59262318, 54.96624779, 43.53223926]])

In [21]:
np.random.seed(2)
np.random.randn(1,4)

array([[-0.41675785, -0.05626683, -2.1361961 ,  1.64027081]])

In [22]:
np.random.seed(2)
np.random.randint(low=0,high=20,size=(1,4))

array([[ 8, 15, 13,  8]])

In [23]:
a

array([1, 2, 5, 4, 5])

In [24]:
b=a+100

In [25]:
b

array([101, 102, 105, 104, 105])

In [26]:
a+b

array([102, 104, 110, 108, 110])

In [27]:
b-100

array([1, 2, 5, 4, 5])

In [28]:
a==b

array([False, False, False, False, False])

In [29]:
a

array([1, 2, 5, 4, 5])

In [30]:
b

array([101, 102, 105, 104, 105])

In [31]:
a.min()

np.int64(1)

In [32]:
a.sum()

np.int64(17)

In [33]:
a.mean()

np.float64(3.4)

In [34]:
a.std()

np.float64(1.624807680927192)